[package]
name = "gifscii"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
ctrlc = "3.4"
image = "0.25.1"
crossterm = "0.27"
anyhow = "1.0"